In [1]:
import numpy as np
import pandas as pd
import s2spy.time

Create an example pandas `DataFrame`

In [2]:
time_index = pd.date_range('20151020', '20211001', freq='15d')
random_data = np.random.random(len(time_index))
example_series = pd.Series(random_data, index=time_index)
example_dataframe = pd.DataFrame(example_series.rename('data1'))
example_dataframe['data2'] = example_dataframe['data1']

Resample the `DataFrame` to an `AdventCalendar`

In [3]:
cal = s2spy.time.AdventCalendar(freq='30d')
dfr = cal.resample(example_dataframe)
dfr

,anchor_year,i_interval,interval,data1,data2,target
0,2016,0,"(2016-10-31, 2016-11-30]",0.481519,0.481519,True
1,2016,1,"(2016-10-01, 2016-10-31]",0.511295,0.511295,False
2,2016,2,"(2016-09-01, 2016-10-01]",0.185496,0.185496,False
3,2016,3,"(2016-08-02, 2016-09-01]",0.603798,0.603798,False
4,2016,4,"(2016-07-03, 2016-08-02]",0.714130,0.714130,False
5,2016,5,"(2016-06-03, 2016-07-03]",0.571613,0.571613,False
6,2016,6,"(2016-05-04, 2016-06-03]",0.785708,0.785708,False
7,2016,7,"(2016-04-04, 2016-05-04]",0.545363,0.545363,False
8,2016,8,"(2016-03-05, 2016-04-04]",0.665551,0.665551,False
9,2016,9,"(2016-02-04, 2016-03-05]",0.724030,0.724030,False
10,2016,10,"(2016-01-05, 2016-02-04]",0.505669,0.505669,False
11,2016,11,"(2015-12-06, 2016-01-05]",0.606113,0.606113,False
12,2017,0,"(2017-10-31, 2017-11-30]",0.152033,0.152033,True
13,2017,1,"(2017-10-01, 2017-10-31]",0.544189,0.544189,False
14,2017,2,"(2017-09-01, 2017-10-01]",0.366564,0.366564,False
15,2017,3,"(2017-08-02, 2017-09-01]",0.198715,0.198715,False
16,2017,4,"(2017-07-03, 2017-08-02]",0.543243,0.543243,False
17,2017,5,"(2017-06-03, 2017-07-03]",0.556358,0.556358,False
18,2017,6,"(2017-05-04, 2017-06-03]",0.120517,0.120517,False
19,2017,7,"(2017-04-04, 2017-05-04]",0.758228,0.758228,False
20,2017,8,"(2017-03-05, 2017-04-04]",0.891166,0.891166,False
21,2017,9,"(2017-02-03, 2017-03-05]",0.714376,0.714376,False
22,2017,10,"(2017-01-04, 2017-02-03]",0.457060,0.457060,False
23,2017,11,"(2016-12-05, 2017-01-04]",0.626218,0.626218,False
24,2018,0,"(2018-10-31, 2018-11-30]",0.398025,0.398025,True
25,2018,1,"(2018-10-01, 2018-10-31]",0.597876,0.597876,False
26,2018,2,"(2018-09-01, 2018-10-01]",0.458945,0.458945,False
27,2018,3,"(2018-08-02, 2018-09-01]",0.685298,0.685298,False
28,2018,4,"(2018-07-03, 2018-08-02]",0.336641,0.336641,False
29,2018,5,"(2018-06-03, 2018-07-03]",0.337557,0.337557,False
30,2018,6,"(2018-05-04, 2018-06-03]",0.565161,0.565161,False
31,2018,7,"(2018-04-04, 2018-05-04]",0.374309,0.374309,False
32,2018,8,"(2018-03-05, 2018-04-04]",0.686092,0.686092,False
33,2018,9,"(2018-02-03, 2018-03-05]",0.513928,0.513928,False
34,2018,10,"(2018-01-04, 2018-02-03]",0.529490,0.529490,False
35,2018,11,"(2017-12-05, 2018-01-04]",0.342474,0.342474,False
36,2019,0,"(2019-10-31, 2019-11-30]",0.677588,0.677588,True
37,2019,1,"(2019-10-01, 2019-10-31]",0.510849,0.510849,False
38,2019,2,"(2019-09-01, 2019-10-01]",0.575809,0.575809,False
39,2019,3,"(2019-08-02, 2019-09-01]",0.329225,0.329225,False
40,2019,4,"(2019-07-03, 2019-08-02]",0.401980,0.401980,False
41,2019,5,"(2019-06-03, 2019-07-03]",0.495501,0.495501,False
42,2019,6,"(2019-05-04, 2019-06-03]",0.930686,0.930686,False
43,2019,7,"(2019-04-04, 2019-05-04]",0.455043,0.455043,False
44,2019,8,"(2019-03-05, 2019-04-04]",0.475035,0.475035,False
45,2019,9,"(2019-02-03, 2019-03-05]",0.835809,0.835809,False
46,2019,10,"(2019-01-04, 2019-02-03]",0.419201,0.419201,False
47,2019,11,"(2018-12-05, 2019-01-04]",0.385569,0.385569,False
48,2020,0,"(2020-10-31, 2020-11-30]",0.589682,0.589682,True
49,2020,1,"(2020-10-01, 2020-10-31]",0.853840,0.853840,False
50,2020,2,"(2020-09-01, 2020-10-01]",0.905703,0.905703,False
51,2020,3,"(2020-08-02, 2020-09-01]",0.399592,0.399592,False
52,2020,4,"(2020-07-03, 2020-08-02]",0.553890,0.553890,False
53,2020,5,"(2020-06-03, 2020-07-03]",0.283430,0.283430,False
54,2020,6,"(2020-05-04, 2020-06-03]",0.560063,0.560063,False
55,2020,7,"(2020-04-04, 2020-05-04]",0.541053,0.541053,False
56,2020,8,"(2020-03-05, 2020-04-04]",0.510428,0.510428,False
57,2020,9,"(2020-02-04, 2020-03-05]",0.604663,0.604663,False
58,2020,10,"(2020-01-05, 2020-02-04]",0.528913,0.528913,False
59,2020,11,"(2019-12-06, 2020-01-05]",0.646299,0.646299,False

Import a splitter class from `sklearn`, and pass it to the wrapper function.

Example: `KFold`

In [4]:
from sklearn.model_selection import KFold
import s2spy.traintest

cv = KFold(n_splits=3)

s2spy.traintest.fold_by_anchor(cv, dfr)

,anchor_year,i_interval,interval,data1,data2,target,fold_0,fold_1,fold_2
0,2016,0,"(2016-10-31, 2016-11-30]",0.481519,0.481519,True,test,train,train
1,2016,1,"(2016-10-01, 2016-10-31]",0.511295,0.511295,False,test,train,train
2,2016,2,"(2016-09-01, 2016-10-01]",0.185496,0.185496,False,test,train,train
3,2016,3,"(2016-08-02, 2016-09-01]",0.603798,0.603798,False,test,train,train
4,2016,4,"(2016-07-03, 2016-08-02]",0.714130,0.714130,False,test,train,train
5,2016,5,"(2016-06-03, 2016-07-03]",0.571613,0.571613,False,test,train,train
6,2016,6,"(2016-05-04, 2016-06-03]",0.785708,0.785708,False,test,train,train
7,2016,7,"(2016-04-04, 2016-05-04]",0.545363,0.545363,False,test,train,train
8,2016,8,"(2016-03-05, 2016-04-04]",0.665551,0.665551,False,test,train,train
9,2016,9,"(2016-02-04, 2016-03-05]",0.724030,0.724030,False,test,train,train
10,2016,10,"(2016-01-05, 2016-02-04]",0.505669,0.505669,False,test,train,train
11,2016,11,"(2015-12-06, 2016-01-05]",0.606113,0.606113,False,test,train,train
12,2017,0,"(2017-10-31, 2017-11-30]",0.152033,0.152033,True,test,train,train
13,2017,1,"(2017-10-01, 2017-10-31]",0.544189,0.544189,False,test,train,train
14,2017,2,"(2017-09-01, 2017-10-01]",0.366564,0.366564,False,test,train,train
15,2017,3,"(2017-08-02, 2017-09-01]",0.198715,0.198715,False,test,train,train
16,2017,4,"(2017-07-03, 2017-08-02]",0.543243,0.543243,False,test,train,train
17,2017,5,"(2017-06-03, 2017-07-03]",0.556358,0.556358,False,test,train,train
18,2017,6,"(2017-05-04, 2017-06-03]",0.120517,0.120517,False,test,train,train
19,2017,7,"(2017-04-04, 2017-05-04]",0.758228,0.758228,False,test,train,train
20,2017,8,"(2017-03-05, 2017-04-04]",0.891166,0.891166,False,test,train,train
21,2017,9,"(2017-02-03, 2017-03-05]",0.714376,0.714376,False,test,train,train
22,2017,10,"(2017-01-04, 2017-02-03]",0.457060,0.457060,False,test,train,train
23,2017,11,"(2016-12-05, 2017-01-04]",0.626218,0.626218,False,test,train,train
24,2018,0,"(2018-10-31, 2018-11-30]",0.398025,0.398025,True,train,test,train
25,2018,1,"(2018-10-01, 2018-10-31]",0.597876,0.597876,False,train,test,train
26,2018,2,"(2018-09-01, 2018-10-01]",0.458945,0.458945,False,train,test,train
27,2018,3,"(2018-08-02, 2018-09-01]",0.685298,0.685298,False,train,test,train
28,2018,4,"(2018-07-03, 2018-08-02]",0.336641,0.336641,False,train,test,train
29,2018,5,"(2018-06-03, 2018-07-03]",0.337557,0.337557,False,train,test,train
30,2018,6,"(2018-05-04, 2018-06-03]",0.565161,0.565161,False,train,test,train
31,2018,7,"(2018-04-04, 2018-05-04]",0.374309,0.374309,False,train,test,train
32,2018,8,"(2018-03-05, 2018-04-04]",0.686092,0.686092,False,train,test,train
33,2018,9,"(2018-02-03, 2018-03-05]",0.513928,0.513928,False,train,test,train
34,2018,10,"(2018-01-04, 2018-02-03]",0.529490,0.529490,False,train,test,train
35,2018,11,"(2017-12-05, 2018-01-04]",0.342474,0.342474,False,train,test,train
36,2019,0,"(2019-10-31, 2019-11-30]",0.677588,0.677588,True,train,test,train
37,2019,1,"(2019-10-01, 2019-10-31]",0.510849,0.510849,False,train,test,train
38,2019,2,"(2019-09-01, 2019-10-01]",0.575809,0.575809,False,train,test,train
39,2019,3,"(2019-08-02, 2019-09-01]",0.329225,0.329225,False,train,test,train
40,2019,4,"(2019-07-03, 2019-08-02]",0.401980,0.401980,False,train,test,train
41,2019,5,"(2019-06-03, 2019-07-03]",0.495501,0.495501,False,train,test,train
42,2019,6,"(2019-05-04, 2019-06-03]",0.930686,0.930686,False,train,test,train
43,2019,7,"(2019-04-04, 2019-05-04]",0.455043,0.455043,False,train,test,train
44,2019,8,"(2019-03-05, 2019-04-04]",0.475035,0.475035,False,train,test,train
45,2019,9,"(2019-02-03, 2019-03-05]",0.835809,0.835809,False,train,test,train
46,2019,10,"(2019-01-04, 2019-02-03]",0.419201,0.419201,False,train,test,train
47,2019,11,"(2018-12-05, 2019-01-04]",0.385569,0.385569,False,train,test,train
48,2020,0,"(2020-10-31, 2020-11-30]",0.589682,0.589682,True,train,train,test
49,2020,1,"(2020-10-01, 2020-10-31]",0.853840,0.853840,False,train,train,test
50,2020,2,"(2020-09-01, 2020-10-01]",0.905703,0.905703,False,train,train,test
51,2020,3,"(2020-08-02, 2020-09-01]",0.399592,0.399592,False,train,train,test
52,2020,4,"(2020-07-03, 2020-08-02]",0.553890,0.553890,False,train,train,test
53,2020,5,"(2020-06-03, 2020-07-03]",0.283430,0.283430,False,train,train,test
54,2020,6,"(2020-05-04, 2020-06-03]",0.560063,0.560063,False,train,train,test
55,2020,7,"(2020-04-04, 2020-05-04]",0.541053,0.541053,False,train,train,test
56,2020,8,"(2020-03-05, 2020-04-04]",0.510428,0.510428,False,train,train,test
57,2020,9,"(2020-02-04, 2020-03-05]",0.604663,0.604663,False,train,train,test
58,2020,10,"(2020-01-05, 2020-02-04]",0.528913,0.528913,False,train,train,test
59,2020,11,"(2019-12-06, 2020-01-05]",0.646299,0.646299,False,train,train,test

Example: `ShuffleSplit`

In [5]:
from sklearn.model_selection import ShuffleSplit

cv = ShuffleSplit(n_splits=3, test_size=0.2)
#note that for shuffle split, folds may not be different

s2spy.traintest.fold_by_anchor(cv, dfr)

,anchor_year,i_interval,interval,data1,data2,target,fold_0,fold_1,fold_2
0,2016,0,"(2016-10-31, 2016-11-30]",0.481519,0.481519,True,train,train,train
1,2016,1,"(2016-10-01, 2016-10-31]",0.511295,0.511295,False,train,train,train
2,2016,2,"(2016-09-01, 2016-10-01]",0.185496,0.185496,False,train,train,train
3,2016,3,"(2016-08-02, 2016-09-01]",0.603798,0.603798,False,train,train,train
4,2016,4,"(2016-07-03, 2016-08-02]",0.714130,0.714130,False,train,train,train
5,2016,5,"(2016-06-03, 2016-07-03]",0.571613,0.571613,False,train,train,train
6,2016,6,"(2016-05-04, 2016-06-03]",0.785708,0.785708,False,train,train,train
7,2016,7,"(2016-04-04, 2016-05-04]",0.545363,0.545363,False,train,train,train
8,2016,8,"(2016-03-05, 2016-04-04]",0.665551,0.665551,False,train,train,train
9,2016,9,"(2016-02-04, 2016-03-05]",0.724030,0.724030,False,train,train,train
10,2016,10,"(2016-01-05, 2016-02-04]",0.505669,0.505669,False,train,train,train
11,2016,11,"(2015-12-06, 2016-01-05]",0.606113,0.606113,False,train,train,train
12,2017,0,"(2017-10-31, 2017-11-30]",0.152033,0.152033,True,train,train,test
13,2017,1,"(2017-10-01, 2017-10-31]",0.544189,0.544189,False,train,train,test
14,2017,2,"(2017-09-01, 2017-10-01]",0.366564,0.366564,False,train,train,test
15,2017,3,"(2017-08-02, 2017-09-01]",0.198715,0.198715,False,train,train,test
16,2017,4,"(2017-07-03, 2017-08-02]",0.543243,0.543243,False,train,train,test
17,2017,5,"(2017-06-03, 2017-07-03]",0.556358,0.556358,False,train,train,test
18,2017,6,"(2017-05-04, 2017-06-03]",0.120517,0.120517,False,train,train,test
19,2017,7,"(2017-04-04, 2017-05-04]",0.758228,0.758228,False,train,train,test
20,2017,8,"(2017-03-05, 2017-04-04]",0.891166,0.891166,False,train,train,test
21,2017,9,"(2017-02-03, 2017-03-05]",0.714376,0.714376,False,train,train,test
22,2017,10,"(2017-01-04, 2017-02-03]",0.457060,0.457060,False,train,train,test
23,2017,11,"(2016-12-05, 2017-01-04]",0.626218,0.626218,False,train,train,test
24,2018,0,"(2018-10-31, 2018-11-30]",0.398025,0.398025,True,train,test,train
25,2018,1,"(2018-10-01, 2018-10-31]",0.597876,0.597876,False,train,test,train
26,2018,2,"(2018-09-01, 2018-10-01]",0.458945,0.458945,False,train,test,train
27,2018,3,"(2018-08-02, 2018-09-01]",0.685298,0.685298,False,train,test,train
28,2018,4,"(2018-07-03, 2018-08-02]",0.336641,0.336641,False,train,test,train
29,2018,5,"(2018-06-03, 2018-07-03]",0.337557,0.337557,False,train,test,train
30,2018,6,"(2018-05-04, 2018-06-03]",0.565161,0.565161,False,train,test,train
31,2018,7,"(2018-04-04, 2018-05-04]",0.374309,0.374309,False,train,test,train
32,2018,8,"(2018-03-05, 2018-04-04]",0.686092,0.686092,False,train,test,train
33,2018,9,"(2018-02-03, 2018-03-05]",0.513928,0.513928,False,train,test,train
34,2018,10,"(2018-01-04, 2018-02-03]",0.529490,0.529490,False,train,test,train
35,2018,11,"(2017-12-05, 2018-01-04]",0.342474,0.342474,False,train,test,train
36,2019,0,"(2019-10-31, 2019-11-30]",0.677588,0.677588,True,train,train,train
37,2019,1,"(2019-10-01, 2019-10-31]",0.510849,0.510849,False,train,train,train
38,2019,2,"(2019-09-01, 2019-10-01]",0.575809,0.575809,False,train,train,train
39,2019,3,"(2019-08-02, 2019-09-01]",0.329225,0.329225,False,train,train,train
40,2019,4,"(2019-07-03, 2019-08-02]",0.401980,0.401980,False,train,train,train
41,2019,5,"(2019-06-03, 2019-07-03]",0.495501,0.495501,False,train,train,train
42,2019,6,"(2019-05-04, 2019-06-03]",0.930686,0.930686,False,train,train,train
43,2019,7,"(2019-04-04, 2019-05-04]",0.455043,0.455043,False,train,train,train
44,2019,8,"(2019-03-05, 2019-04-04]",0.475035,0.475035,False,train,train,train
45,2019,9,"(2019-02-03, 2019-03-05]",0.835809,0.835809,False,train,train,train
46,2019,10,"(2019-01-04, 2019-02-03]",0.419201,0.419201,False,train,train,train
47,2019,11,"(2018-12-05, 2019-01-04]",0.385569,0.385569,False,train,train,train
48,2020,0,"(2020-10-31, 2020-11-30]",0.589682,0.589682,True,test,train,train
49,2020,1,"(2020-10-01, 2020-10-31]",0.853840,0.853840,False,test,train,train
50,2020,2,"(2020-09-01, 2020-10-01]",0.905703,0.905703,False,test,train,train
51,2020,3,"(2020-08-02, 2020-09-01]",0.399592,0.399592,False,test,train,train
52,2020,4,"(2020-07-03, 2020-08-02]",0.553890,0.553890,False,test,train,train
53,2020,5,"(2020-06-03, 2020-07-03]",0.283430,0.283430,False,test,train,train
54,2020,6,"(2020-05-04, 2020-06-03]",0.560063,0.560063,False,test,train,train
55,2020,7,"(2020-04-04, 2020-05-04]",0.541053,0.541053,False,test,train,train
56,2020,8,"(2020-03-05, 2020-04-04]",0.510428,0.510428,False,test,train,train
57,2020,9,"(2020-02-04, 2020-03-05]",0.604663,0.604663,False,test,train,train
58,2020,10,"(2020-01-05, 2020-02-04]",0.528913,0.528913,False,test,train,train
59,2020,11,"(2019-12-06, 2020-01-05]",0.646299,0.646299,False,test,train,train

Example: `TimeSeriesSplit`

In [6]:
from sklearn.model_selection import TimeSeriesSplit

cv = TimeSeriesSplit(n_splits=4)

s2spy.traintest.fold_by_anchor(cv, dfr)

,anchor_year,i_interval,interval,data1,data2,target,fold_0,fold_1,fold_2,fold_3
0,2016,0,"(2016-10-31, 2016-11-30]",0.481519,0.481519,True,train,train,train,train
1,2016,1,"(2016-10-01, 2016-10-31]",0.511295,0.511295,False,train,train,train,train
2,2016,2,"(2016-09-01, 2016-10-01]",0.185496,0.185496,False,train,train,train,train
3,2016,3,"(2016-08-02, 2016-09-01]",0.603798,0.603798,False,train,train,train,train
4,2016,4,"(2016-07-03, 2016-08-02]",0.714130,0.714130,False,train,train,train,train
5,2016,5,"(2016-06-03, 2016-07-03]",0.571613,0.571613,False,train,train,train,train
6,2016,6,"(2016-05-04, 2016-06-03]",0.785708,0.785708,False,train,train,train,train
7,2016,7,"(2016-04-04, 2016-05-04]",0.545363,0.545363,False,train,train,train,train
8,2016,8,"(2016-03-05, 2016-04-04]",0.665551,0.665551,False,train,train,train,train
9,2016,9,"(2016-02-04, 2016-03-05]",0.724030,0.724030,False,train,train,train,train
10,2016,10,"(2016-01-05, 2016-02-04]",0.505669,0.505669,False,train,train,train,train
11,2016,11,"(2015-12-06, 2016-01-05]",0.606113,0.606113,False,train,train,train,train
12,2017,0,"(2017-10-31, 2017-11-30]",0.152033,0.152033,True,test,train,train,train
13,2017,1,"(2017-10-01, 2017-10-31]",0.544189,0.544189,False,test,train,train,train
14,2017,2,"(2017-09-01, 2017-10-01]",0.366564,0.366564,False,test,train,train,train
15,2017,3,"(2017-08-02, 2017-09-01]",0.198715,0.198715,False,test,train,train,train
16,2017,4,"(2017-07-03, 2017-08-02]",0.543243,0.543243,False,test,train,train,train
17,2017,5,"(2017-06-03, 2017-07-03]",0.556358,0.556358,False,test,train,train,train
18,2017,6,"(2017-05-04, 2017-06-03]",0.120517,0.120517,False,test,train,train,train
19,2017,7,"(2017-04-04, 2017-05-04]",0.758228,0.758228,False,test,train,train,train
20,2017,8,"(2017-03-05, 2017-04-04]",0.891166,0.891166,False,test,train,train,train
21,2017,9,"(2017-02-03, 2017-03-05]",0.714376,0.714376,False,test,train,train,train
22,2017,10,"(2017-01-04, 2017-02-03]",0.457060,0.457060,False,test,train,train,train
23,2017,11,"(2016-12-05, 2017-01-04]",0.626218,0.626218,False,test,train,train,train
24,2018,0,"(2018-10-31, 2018-11-30]",0.398025,0.398025,True,skip,test,train,train
25,2018,1,"(2018-10-01, 2018-10-31]",0.597876,0.597876,False,skip,test,train,train
26,2018,2,"(2018-09-01, 2018-10-01]",0.458945,0.458945,False,skip,test,train,train
27,2018,3,"(2018-08-02, 2018-09-01]",0.685298,0.685298,False,skip,test,train,train
28,2018,4,"(2018-07-03, 2018-08-02]",0.336641,0.336641,False,skip,test,train,train
29,2018,5,"(2018-06-03, 2018-07-03]",0.337557,0.337557,False,skip,test,train,train
30,2018,6,"(2018-05-04, 2018-06-03]",0.565161,0.565161,False,skip,test,train,train
31,2018,7,"(2018-04-04, 2018-05-04]",0.374309,0.374309,False,skip,test,train,train
32,2018,8,"(2018-03-05, 2018-04-04]",0.686092,0.686092,False,skip,test,train,train
33,2018,9,"(2018-02-03, 2018-03-05]",0.513928,0.513928,False,skip,test,train,train
34,2018,10,"(2018-01-04, 2018-02-03]",0.529490,0.529490,False,skip,test,train,train
35,2018,11,"(2017-12-05, 2018-01-04]",0.342474,0.342474,False,skip,test,train,train
36,2019,0,"(2019-10-31, 2019-11-30]",0.677588,0.677588,True,skip,skip,test,train
37,2019,1,"(2019-10-01, 2019-10-31]",0.510849,0.510849,False,skip,skip,test,train
38,2019,2,"(2019-09-01, 2019-10-01]",0.575809,0.575809,False,skip,skip,test,train
39,2019,3,"(2019-08-02, 2019-09-01]",0.329225,0.329225,False,skip,skip,test,train
40,2019,4,"(2019-07-03, 2019-08-02]",0.401980,0.401980,False,skip,skip,test,train
41,2019,5,"(2019-06-03, 2019-07-03]",0.495501,0.495501,False,skip,skip,test,train
42,2019,6,"(2019-05-04, 2019-06-03]",0.930686,0.930686,False,skip,skip,test,train
43,2019,7,"(2019-04-04, 2019-05-04]",0.455043,0.455043,False,skip,skip,test,train
44,2019,8,"(2019-03-05, 2019-04-04]",0.475035,0.475035,False,skip,skip,test,train
45,2019,9,"(2019-02-03, 2019-03-05]",0.835809,0.835809,False,skip,skip,test,train
46,2019,10,"(2019-01-04, 2019-02-03]",0.419201,0.419201,False,skip,skip,test,train
47,2019,11,"(2018-12-05, 2019-01-04]",0.385569,0.385569,False,skip,skip,test,train
48,2020,0,"(2020-10-31, 2020-11-30]",0.589682,0.589682,True,skip,skip,skip,test
49,2020,1,"(2020-10-01, 2020-10-31]",0.853840,0.853840,False,skip,skip,skip,test
50,2020,2,"(2020-09-01, 2020-10-01]",0.905703,0.905703,False,skip,skip,skip,test
51,2020,3,"(2020-08-02, 2020-09-01]",0.399592,0.399592,False,skip,skip,skip,test
52,2020,4,"(2020-07-03, 2020-08-02]",0.553890,0.553890,False,skip,skip,skip,test
53,2020,5,"(2020-06-03, 2020-07-03]",0.283430,0.283430,False,skip,skip,skip,test
54,2020,6,"(2020-05-04, 2020-06-03]",0.560063,0.560063,False,skip,skip,skip,test
55,2020,7,"(2020-04-04, 2020-05-04]",0.541053,0.541053,False,skip,skip,skip,test
56,2020,8,"(2020-03-05, 2020-04-04]",0.510428,0.510428,False,skip,skip,skip,test
57,2020,9,"(2020-02-04, 2020-03-05]",0.604663,0.604663,False,skip,skip,skip,test
58,2020,10,"(2020-01-05, 2020-02-04]",0.528913,0.528913,False,skip,skip,skip,test
59,2020,11,"(2019-12-06, 2020-01-05]",0.646299,0.646299,False,skip,skip,skip,test